#!/bin/sh
set -e

docker tag $DOCKER_USERNAME/$DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:latest
docker tag $DOCKER_USERNAME/$DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_TAG
echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$TRAVIS_TAG
docker rmi $DOCKER_USERNAME/$DOCKER_IMAGE